config/routes.rb
Rails.application.routes.draw do
  resources :data_tabs
  resources :simulation_steps
  resources :simulations
  resources :alerts
  resources :time_flow_monitors
  resources :report_items
  resources :reports
  resources :event_stream_fields
  resources :event_streams
  resources :projects
  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alert.rb
class Alert < ApplicationRecord
  belongs_to :project
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_stream.rb
class EventStream < ApplicationRecord
end

app/models/event_stream_field.rb
class EventStreamField < ApplicationRecord
  belongs_to :event_stream
end

app/models/organisation.rb
class Organisation < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organisation
  validates_presence_of :name
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/report_item.rb
class ReportItem < ApplicationRecord
  belongs_to :report
end

app/models/simulation.rb
class Simulation < ApplicationRecord
  belongs_to :project
end

app/models/simulation_step.rb
class SimulationStep < ApplicationRecord
  belongs_to :simulation
end

app/models/time_flow_monitor.rb
class TimeFlowMonitor < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :company_name

  validates_presence_of :company_name, :first_name, :last_name

  belongs_to :organisation, optional: true
  before_create :create_organisation

  def full_name
    first_name.to_s + " " + last_name.to_s
  end

  private
    def create_organisation
      self.organisation = Organisation.create(name: company_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_tabs_helper.rb
module DataTabsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/views/shared/_header.html.erb
<header class="main-header">
  <!-- main header -->
  <div class="container">
    <div class="row md-header">
      <div class="col-lg-5 col-md-5 pr-md-0">
        <!-- left Links -->
        <ul class="nav left_side">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <%= image_tag('52.png') %>
              <%= current_user.try(:full_name) %>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-2 text-center">
        <div class="header-logo">
          <a class="navbar-brand" href="#">
            <%= image_tag('logo.png') %>
          </a>
        </div>
      </div>
      <div class="col-lg-5 col-md-5 pl-md-0">
        <!-- right Links -->
        <ul class="nav justify-content-end right-side">
          <li class="nav-item">
            <a class="nav-link" href="<%= destroy_user_session_path %>">
              <%= image_tag('53.png') %>
            </a>
          </li>                
        </ul>
      </div>
    </div>
    <div class="row mb-header">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <!-- <a class="navbar-brand" href="#">
              <%#= image_tag('logo.png') %>
            </a> -->
            <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="slide-collapse" data-target="#slide-navbar-collapse" aria-expanded="false">
              <i class="fa fa-bars" aria-hidden="true"></i>
            </button> -->
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="slide-navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <%= image_tag('2.png') %>Project
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <%= image_tag('3.png') %>Data
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <%= image_tag('4.png') %>Manage
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <%= image_tag('5.png') %>Reporting
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <%= image_tag('6.png') %>Window
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <%= image_tag('7.png') %>Help
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <%= image_tag('menu_icon_logout.png') %>Logout
                </a>
              </li>
            </ul> 
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
      </nav>
      <div class="menu-overlay"></div>
    </div>
  </div>
  <!-- header end -->
</header>

app/views/shared/_sub_header.html.erb
<!--Transparent header-->
<section class="black_header">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-4">
        <div class="customer_value">
          <%= image_tag('67.png') %>
          <h4 class="mb-0">Customer Value Examination</h4>
        </div>
      </div>
      <div class="col-lg-8 col-md-8 text-right"> 
        <ul>
          <li class="<%= params[:controller] == 'event_streams' ? 'active' : '' %>">
            <a href="<%= event_streams_path %>">
              <%= image_tag('61.png') %>Events
            </a>
          </li>
          <li class="<%= params[:controller] == 'data_tabs' ? 'active' : '' %>">
            <a href="<%= data_tabs_path %>">
              <%= image_tag('62.png') %>Data
            </a>
          </li>
          <li class="<%= params[:controller] == 'reports' ? 'active' : '' %>">
            <a href="<%= reports_path %>">
              <%= image_tag('64.png') %>Reportaing
            </a>
          </li>
          <li class="<%= params[:controller] == 'time_flow_monitors' ? 'active' : '' %>">
            <a href="<%= time_flow_monitors_path %>">
              <%= image_tag('65.png') %>Monitors
            </a>
          </li>
          <li class="<%= params[:controller] == 'alerts' ? 'active' : '' %>">
            <a href="<%= alerts_path %>">
              <%= image_tag('66.png') %>Alerts
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!--Transparent header-->