config/routes.rb
Rails.application.routes.draw do
  resources :data_tabs
  resources :simulation_steps
  resources :simulations
  resources :alerts
  resources :time_flow_monitors
  resources :report_items
  resources :reports
  resources :event_stream_fields
  resources :event_streams
  resources :projects
  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alert.rb
class Alert < ApplicationRecord
  belongs_to :project
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_stream.rb
class EventStream < ApplicationRecord
end

app/models/event_stream_field.rb
class EventStreamField < ApplicationRecord
  belongs_to :event_stream
end

app/models/organisation.rb
class Organisation < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organisation
  validates_presence_of :name
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/report_item.rb
class ReportItem < ApplicationRecord
  belongs_to :report
end

app/models/simulation.rb
class Simulation < ApplicationRecord
  belongs_to :project
end

app/models/simulation_step.rb
class SimulationStep < ApplicationRecord
  belongs_to :simulation
end

app/models/time_flow_monitor.rb
class TimeFlowMonitor < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :company_name

  validates_presence_of :company_name, :first_name, :last_name

  belongs_to :organisation, optional: true
  before_create :create_organisation

  def full_name
    first_name.to_s + " " + last_name.to_s
  end

  private
    def create_organisation
      self.organisation = Organisation.create(name: company_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/report_items_controller.rb
class ReportItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_report_item, only: %i[ show edit update destroy ]

  # GET /report_items or /report_items.json
  def index
    @report_items = ReportItem.all
  end

  # GET /report_items/1 or /report_items/1.json
  def show
  end

  # GET /report_items/new
  def new
    @report_item = ReportItem.new
  end

  # GET /report_items/1/edit
  def edit
  end

  # POST /report_items or /report_items.json
  def create
    @report_item = ReportItem.new(report_item_params)

    respond_to do |format|
      if @report_item.save
        format.html { redirect_to @report_item, notice: "Report item was successfully created." }
        format.json { render :show, status: :created, location: @report_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /report_items/1 or /report_items/1.json
  def update
    respond_to do |format|
      if @report_item.update(report_item_params)
        format.html { redirect_to @report_item, notice: "Report item was successfully updated." }
        format.json { render :show, status: :ok, location: @report_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /report_items/1 or /report_items/1.json
  def destroy
    @report_item.destroy
    respond_to do |format|
      format.html { redirect_to report_items_url, notice: "Report item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report_item
      @report_item = ReportItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_item_params
      params.require(:report_item).permit(:name, :description, :report_id, :report_type)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_tabs_helper.rb
module DataTabsHelper
end

app/helpers/event_streams_helper.rb
module EventStreamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/report_items_helper.rb
module ReportItemsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/views/report_items/_form.html.erb
<%= form_with(model: report_item) do |form| %>
  <% if report_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report_item.errors.count, "error") %> prohibited this report_item from being saved:</h2>

      <ul>
        <% report_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :report_id %>
    <%= form.text_field :report_id %>
  </div>

  <div class="field">
    <%= form.label :report_type %>
    <%= form.text_field :report_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/report_items/edit.html.erb
<h1>Editing Report Item</h1>

<%= render 'form', report_item: @report_item %>

<%= link_to 'Show', @report_item %> |
<%= link_to 'Back', report_items_path %>

app/views/report_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Report Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Report</th>
      <th>Report type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @report_items.each do |report_item| %>
      <tr>
        <td><%= report_item.name %></td>
        <td><%= report_item.description %></td>
        <td><%= report_item.report_id %></td>
        <td><%= report_item.report_type %></td>
        <td><%= link_to 'Show', report_item %></td>
        <td><%= link_to 'Edit', edit_report_item_path(report_item) %></td>
        <td><%= link_to 'Destroy', report_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report Item', new_report_item_path %>

app/views/report_items/new.html.erb
<h1>New Report Item</h1>

<%= render 'form', report_item: @report_item %>

<%= link_to 'Back', report_items_path %>

app/views/report_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @report_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @report_item.description %>
</p>

<p>
  <strong>Report:</strong>
  <%= @report_item.report_id %>
</p>

<p>
  <strong>Report type:</strong>
  <%= @report_item.report_type %>
</p>

<%= link_to 'Edit', edit_report_item_path(@report_item) %> |
<%= link_to 'Back', report_items_path %>