config/routes.rb
Rails.application.routes.draw do
  resources :data_tabs
  resources :simulation_steps
  resources :simulations
  resources :alerts
  resources :time_flow_monitors
  resources :report_items
  resources :reports
  resources :event_stream_fields
  resources :event_streams
  resources :projects
  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alert.rb
class Alert < ApplicationRecord
  belongs_to :project
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_stream.rb
class EventStream < ApplicationRecord
end

app/models/event_stream_field.rb
class EventStreamField < ApplicationRecord
  belongs_to :event_stream
end

app/models/organisation.rb
class Organisation < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organisation
  validates_presence_of :name
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/report_item.rb
class ReportItem < ApplicationRecord
  belongs_to :report
end

app/models/simulation.rb
class Simulation < ApplicationRecord
  belongs_to :project
end

app/models/simulation_step.rb
class SimulationStep < ApplicationRecord
  belongs_to :simulation
end

app/models/time_flow_monitor.rb
class TimeFlowMonitor < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :company_name

  validates_presence_of :company_name, :first_name, :last_name

  belongs_to :organisation, optional: true
  before_create :create_organisation

  def full_name
    first_name.to_s + " " + last_name.to_s
  end

  private
    def create_organisation
      self.organisation = Organisation.create(name: company_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_report, only: %i[ show edit update destroy ]

  # GET /reports or /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1 or /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports or /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:name, :description, :project)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_tabs_helper.rb
module DataTabsHelper
end

app/helpers/event_streams_helper.rb
module EventStreamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/report_items_helper.rb
module ReportItemsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :project %>
    <%= form.text_field :project %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/new.html.erb
<!--Event Stream-->
<section class="event_stream">
  <div class="container">
      <div class="row">
          <div class="col-md-12 pb-3">
              <a href="welcome.html" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>
              <div class="new_event text-center pt-5"> 
                  <h3 class="pb-5">New Report</h3> 
                  <ul class="nav nav-tabs justify-content-center pb-5" id="myTab" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link " id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><%= image_tag("eye.svg", class: "tab_img") %> Show</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">
                        <%= image_tag("edit-3.svg", class: "tab_img") %> Edit</a>
                    </li> 
                  </ul>
                  <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                      <!--  <form> -->
                          <div class="row">
                              <div class="col-md-6">
                                  <div class="form-group"> 
                                      <input type="text" class="form-control" placeholder="Report Name"> 
                                  </div>
                              </div>
                              <div class="col-md-6">
                                  <div class="form-group"> 
                                      <input type="text" class="form-control" placeholder="Report Description"> 
                                  </div>
                              </div> 
                              <div class="col-md-12 text-center">
                                      <button class="import_btn mt-4 mb-3 ml-2" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus" aria-hidden="true" ></i>Add Items</button>
                                  </div>
                              <div class="col-md-12 ">
                                  <div class="border_final mt-4">
                                      <button class="project_btn mt-5 mb-5 bg-gray">Submit</button>
                                  </div>
                              </div>
                          </div>
                      <!-- </form>  -->
                    </div>
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                         <form>
                              <div class="row">
                                  <div class="col-md-6">
                                      <div class="form-group"> 
                                          <input type="text" class="form-control" placeholder="Report Name"> 
                                      </div>
                                  </div>
                                  <div class="col-md-6">
                                      <div class="form-group"> 
                                          <input type="text" class="form-control" placeholder="Report Description"> 
                                      </div>
                                  </div> 
                                  <div class="col-md-12 text-center">
                                      <button class="import_btn mt-4 mb-3 ml-2" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus" aria-hidden="true" ></i>Add Items</button>
                                  </div>
                                  <div class="col-md-12 ">
                                      <div class="border_final mt-4">
                                          <button class="project_btn mt-5 mb-5 bg-gray">Submit</button>
                                      </div>
                                  </div>
                              </div>
                          </form>
                    </div> 
                  </div> 
              </div>
          </div>
      </div>
  </div>
</section>
<!--Event Stream--> 


<!-- The Modal for new item Report -->
<div class="modal fade" id="myModal">
<div class="modal-dialog modal-lg">
<div class="modal-content">
  
    <button type="button" class="close text-right pl-2 pr-3 pt-2" data-dismiss="modal">&times;</button>
  <!-- Modal body -->
  <div class="modal-body">
      <h4 class="modal-title text-center">Add A New Report Item</h4>
    <ul>
        <li>
          <input type="checkbox" id="myCheckbox1" />
          <label for="myCheckbox1"><%= image_tag("92.png") %></label>
          <h6>Data Table</h6>
        </li>
        <li> 
          <input type="checkbox" id="myCheckbox2" />
          <label for="myCheckbox2"><%= image_tag("93.png") %></label>
          <h6>Time Series</h6>
        </li>
        <li> 
          <input type="checkbox" id="myCheckbox3" />
          <label for="myCheckbox3"><%= image_tag("94.png") %></label>
          <h6>Metric</h6>
        </li>
        <li> 
          <input type="checkbox" id="myCheckbox4" />
          <label for="myCheckbox4"><%= image_tag("95.png") %></label>
          <h6>Bar Chart</h6>
        </li>
        <li> 
          <input type="checkbox" id="myCheckbox5" />
          <label for="myCheckbox5"><%= image_tag("96.png") %></label>
          <h6>Histogram</h6>
        </li>
        <li> 
          <input type="checkbox" id="myCheckbox6" />
          <label for="myCheckbox6"><%= image_tag("97.png") %></label>
          <h6>Pie Chart</h6>
        </li>
        <li> 
          <input type="checkbox" id="myCheckbox7" />
          <label for="myCheckbox7"><%= image_tag("98.png") %></label>
          <h6>Scatter Plot</h6>
        </li>
        <li> 
          <input type="checkbox" id="myCheckbox8" />
          <label for="myCheckbox8"><%= image_tag("99.png") %></label>
          <h6>SQL Query</h6>
        </li>
        <li> 
          <input type="checkbox" id="myCheckbox9" />
          <label for="myCheckbox9"><%= image_tag("110.png") %></label>
          <h6>External Source</h6>
        </li>
        <li> 
          <input type="checkbox" id="myCheckbox10" />
          <label for="myCheckbox10"><%= image_tag("115.png") %></label>
          <h6>External Source</h6>
        </li>
        <li> 
          <input type="checkbox" id="myCheckbox10" />
          <label for="myCheckbox10"><%= image_tag("111.png") %></label>
          <h6>External Source</h6>
        </li>
        <li> 
          <input type="checkbox" id="myCheckbox10" />
          <label for="myCheckbox10"><%= image_tag("93.png") %></label>
          <h6>Alerts</h6>
        </li>
      </ul>
      <button class="modal_add">Add</button>
  </div>
   
  
</div>
</div>
</div>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @report.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @report.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @report.project %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>